function [Gamma1_teorico,Gamma2_teorico] = Wilson(Parametros,x1_experimental)

Gamma1_teorico=exp(-log(x1_experimental+Parametros(1).*(1-x1_experimental))+...
    (1-x1_experimental).*(Parametros(1)./(x1_experimental+Parametros(1).*(1-x1_experimental)))-...
    (1-x1_experimental).*(Parametros(2)./(x1_experimental*Parametros(2)+(1-x1_experimental))));

Gamma2_teorico=exp(-log(x1_experimental.*Parametros(2)+(1-x1_experimental))-...
    (x1_experimental).*(Parametros(1)./(x1_experimental+Parametros(1).*(1-x1_experimental)))+...
    (x1_experimental).*(Parametros(2)./(x1_experimental*Parametros(2)+(1-x1_experimental))));

end

